#! /usr/bin/env ruby

# get-news: a script to retrieve news items from rubyforge.org
# This program is copyright 2009 by Vincent Fourmond.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301
# USA

require 'net/http'
require 'yaml'

id = ARGV[0] || "1477"          # group id, work on SciYAG by default
                                # for now

http = Net::HTTP.new("rubyforge.org")

resp, data = http.get("/news/?group_id=#{id}")

post_ids = []

data.gsub(/<a\s+href=["']([^"']+)/) do |m|
  if $1 =~ /\/forum\/forum\.php\?forum_id=(\d+)/
    post_ids << $1.to_i
  end
end

STDERR.puts "Found #{post_ids.size} posts"

posts = []

# Fine, now we have the forums corresponding to the posts. Next thing,
# we get the texts from the forums.
i = 1
for id in post_ids
  STDERR.puts "Downloading post #{i} (id: #{id})"
  resp, data = http.get("/forum/forum.php?forum_id=#{id}")
  if data =~ /<strong>(.*?)<p>(.*?)<\/p>/m
    header, contents = $1, $2
    post = {}
    for k,v in {
        :author => /Posted\s*By/i, 
        :title => /Summary/i,
        :date => /Date/i,
      }
      if header =~ /#{v}\s*:\s*<\/strong>\s*(?:<a[^>]+>)?\s*(.*?)\s*(?:<\/a>)?\s*<br\s*\/>/
          post[k] = $1
      end
    end
    post[:id] = id
    post[:contents] = contents.gsub(/[\r\t]/,'').gsub(/<br\s*\/>/,"\n").
      gsub(/\A\n+|\n+\z/,'').gsub(/(--[\w-]+)/, '@\1@') # The last one for command-line arguments, if 
    if post[:date] =~ /(\d+)-(\d+)-(\d+)\s+(\d+):(\d+)/
      post[:date] = Time.local($1.to_i, $2.to_i, $3.to_i,
                             $4.to_i, $5.to_i)
      post[:date] += 5*3600       # 5 hours time difference with the
                                # site of rubyforge...
    end
    posts << post
  end
  i += 1
end

puts YAML.dump(posts)
